//
//  ViewController.swift
//  List_Master
//
//  Created by VencleDeng on 20/5/19.
//  Copyright © 2019 au.edu.uts. All rights reserved.
//

import UIKit
/*HomeController is the view controller for home view*/
class HomeController: UIViewController {

    @IBOutlet weak var listTable: UITableView!
    @IBOutlet weak var editButton: UIBarButtonItem!
    @IBOutlet weak var sortButton: UIBarButtonItem!
    @IBOutlet weak var searchBar: UISearchBar!
    
    var isSorted = false //track sort status
    var isSearched = false //track search status
    var shownTodoList = [TodoItem]() //define the todo list shown in
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupTableView()
        setupSearchBar()
        do{
             try TodoList.loadTodos()
        }catch let error{
            alert(title: "Error!!!", message: error as! String, view: self)
        }
        shownTodoList = TodoList.todos
    }
    override func viewDidAppear(_ animated: Bool) {
        TodoList.saveTodos()
        listTable.reloadData()
    }
    /*editAction() handle the event generated by clicking 'Edit' button. when the button is clicked, the table view will be in editing mode*/
    @IBAction func editAction(_ sender: UIBarButtonItem) {
        self.listTable.isEditing = !self.listTable.isEditing
        sender.title = (self.listTable.isEditing) ? "Done" : "Edit"
    }
    /*sortAction() handle the event generated by clicking 'Sort' button. when the button is clicked, the list is sorted by priority*/
    @IBAction func sortAction(_ sender: Any) {
        sortButton.title = sortButton.title == "Sort" ? "Unsort":"Sort"
        if sortButton.title == "Unsort" {
            isSorted = true
            TodoList.SortByPriority()
            listTable.reloadData()
        } else {
            isSorted = false
            listTable.reloadData()
        }
    }
    
    
   /*set up the table view*/
    func setupTableView() {
        listTable.delegate = self
        listTable.dataSource = self
    }
    /*set up search bar*/
    func setupSearchBar() {
        searchBar.delegate = self
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }
    /*prepare() is an overide function that pass the selected todo's ID to todo detail view*/
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if segue.identifier == "HomeToDetail" {
             let destVC = segue.destination as! TodoDetailViewcontroller
            destVC.todoId = sender as? UUID
        }
       
    }


}
/*extension that set up the attributes of table view and search bar*/
extension HomeController: UITableViewDataSource, UITableViewDelegate, UISearchBarDelegate{
    /*move todo in editing mode*/
    func tableView(_ tableView: UITableView, moveRowAt sourceIndexPath: IndexPath, to destinationIndexPath: IndexPath) {
            let moveObjectTemp = TodoList.todos[sourceIndexPath.item]
            TodoList.todos.remove(at: sourceIndexPath.item)
            TodoList.todos.insert(moveObjectTemp, at: destinationIndexPath.item)
            TodoList.saveTodos()
       
    }
    func tableView(_ tableView: UITableView, canMoveRowAt indexPath: IndexPath) -> Bool {
        return isSorted ? false : true
    }
    /*reset number of rows in table (avoid the changes in row caused by search result)*/
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
       if !isSearched{
            shownTodoList = isSorted ? TodoList.sortedTodos : TodoList.todos
        }
        return shownTodoList.count
    }
    /*if the todo is sorted, then display sorted result. If user is search for todos, then search result will be displayed*/
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "cell", for: indexPath) as! TodoTableViewCell    //define the prototype cell as TodoTableViewCell
        if !isSearched{
            shownTodoList = isSorted ? TodoList.sortedTodos : TodoList.todos
        }
        print(shownTodoList.count)
        cell.todoTitle.text = shownTodoList[indexPath.item].title
        cell.todoPriority.text = shownTodoList[indexPath.item].priority
        if shownTodoList[indexPath.row].completed {
            cell.accessoryType = .checkmark
        }else{
            cell.accessoryType = .none
        }
    
        
        return cell
    }
    /*delete the todo in editing mode, from both todo list table and todo list model*/
    func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCell.EditingStyle, forRowAt indexPath: IndexPath) {
        
        if (editingStyle == .delete) {
            let todoID = shownTodoList[indexPath.item].id
            TodoList.deleteTodo(todoID: todoID)
            TodoList.saveTodos()
            listTable.deleteRows(at: [indexPath], with: .automatic)
            
        }
    }
    /*when a todo cell is tapped, it will jump to todo detail view*/
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
       let todo = TodoList.todos[indexPath.row]
        performSegue(withIdentifier: "HomeToDetail", sender: todo.id)
    }
    /*define the search function*/
    func searchBar(_ searchBar: UISearchBar, textDidChange searchText: String) {
        
        guard !searchText.isEmpty else {
            isSearched = false
            listTable.reloadData()
            return
        }
        isSearched = true
        shownTodoList = shownTodoList.filter({ todo -> Bool in
            todo.title.lowercased().contains(searchText.lowercased())   // filter out the todos which is not matched the input in search bar
        })
        listTable.reloadData()
    }
    
    
}
