//
//  AddItemController.swift
//  List_Master
//
//  Created by VencleDeng on 20/5/19.
//  Copyright © 2019 au.edu.uts. All rights reserved.
//

/*
 AddItemController is the view controoler for add todo item view
 */
import UIKit
import Foundation
class AddItemController: UIViewController{
    @IBOutlet weak var priorityPicker: UIPickerView!
    @IBOutlet weak var titleText: UITextField!
    @IBOutlet weak var descriptionText: UITextView!
    @IBOutlet weak var datePicker: UIDatePicker!
    
    let priority = ["Low", "Medium", "High"] //define a array of priority
    var selectedPriority:String = "Low"   //store the priority selected by user
    var selectedDate:String? //store date selected by user
    
    /*the following method handle the event when user click on 'Add' button on navigation bar*/
    @IBAction func addList(_ sender: UIBarButtonItem) {
        let title = titleText.text
        let description = descriptionText.text ?? ""
        let priority = selectedPriority
        let date = selectedDate!
        if (title == ""){
            alert(title: "Enter todo title", message: "You muct enter a title!!", view: self)
          
        }else if (description == ""){
            alert(title: "Enter Todo description", message: "You muat descript your todo!!", view: self)
            
        }
        else{
            
            let newItem: TodoItem = TodoItem(id: UUID(), title: title!, description: description, priority: priority, date: date)
            TodoList.addTodo(newTodo: newItem)
            self.navigationController?.popViewController(animated: true)
        }     //add new todo to todo list and navigate back to home page
        
    }
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        self.priorityPicker.delegate = self
        self.priorityPicker.dataSource = self
        setupPickers()
        setupTextView()
       
    }
    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        super.touchesBegan(touches, with: event)
        self.view.endEditing(true)
    }
    /*setupTextView() is to set up the attribute of description text view*/
    func setupTextView() {
        descriptionText.layer.borderColor = UIColor.gray.cgColor
        descriptionText.layer.borderWidth = 0.3
        descriptionText.layer.cornerRadius = 2.0
        descriptionText.clipsToBounds = true
    }
    /*setupPicker() is to set up date picker and their default value*/
    func setupPickers(){
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd HH:mm:ss"
        selectedDate = formatter.string(from: datePicker.date)
        priorityPicker.selectedRow(inComponent: 0)  //set 'Low' as default priority in the picker view
    }
    /*selectedDate() handle the change event generated by changing date in date picker*/
    @IBAction func selectedDate(_ sender: Any) {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd HH:mm:ss"
        selectedDate = formatter.string(from: datePicker.date)
    }
}
/*The following extension is to set up attributes of picker view used in this view*/
extension AddItemController:UIPickerViewDataSource, UIPickerViewDelegate {
    func numberOfComponents(in pickerView: UIPickerView) -> Int {
        return 1               //there is only one component in priority picker view
    }
    func pickerView(_ pickerView: UIPickerView, titleForRow row: Int, forComponent component: Int) -> String? {
        return priority[row]      //user can choose from the element in priority array, incluing "Low", "Medium" and "High"
    }
    func pickerView(_ pickerView: UIPickerView, numberOfRowsInComponent component: Int) -> Int {
        return priority.count      //the number of rows in the picker should match the length in todo list
    }
    func pickerView(_ pickerView: UIPickerView, didSelectRow row: Int, inComponent component: Int) {
        selectedPriority = priority[row]      //once user select a row, the value in that row is assigned to selectedPriority
    }
}
